env = Environment(
    CCFLAGS=['-Wall', '-Wextra'],
    CPPPATH='.',
)

flags = {
    'debug': { 'CCFLAGS': ['-O0', '-ggdb', '-Werror'] },
    'release': { 'CCFLAGS': ['-O2'] },
}

config = ARGUMENTS.get('config', 'debug')
env.MergeFlags(flags[config])
for var in 'CXX', 'CC':
    try:
        env[var] = ARGUMENTS[var]
    except KeyError:
        pass

sdlenv = env.Clone()
sdlenv.ParseConfig('sdl-config --cflags')

env.ParseConfig('sdl-config --libs')

env.Program('raycast', [
    sdlenv.Object('main.c'),
    'draw.c',
    'draw_rect.c',
])
